---

# have to:
# - install/enable xcode
# - install macports
# - set macports in /etc/paths.d/ ?

- name: Install base packages
  macports: name={{item}} state=active
  with_items:
    - zsh
    - MacVim
    - ctags
    - tmux
    - dejavu-fonts
    - git
    - mercurial
  tags: packages, install


