---

- name: Install base packages
  apt: name={{item}} state=installed
  with_items:
    - build-essential
    - git
    - mercurial
    - zsh
    - tmux
    - vim
    - silversearcher-ag
    - exuberant-ctags
    - unattended-upgrades
  tags: packages, install

- name: Install GUI packages
  when: gui_enabled
  apt: name={{item}} state=installed
  with_items:
    - lightdm
    - rxvt-unicode-256color
    - i3
    - xautolock
    - fonts-dejavu-extra
    - fonts-opensymbol
    - scrot
    - vim-gtk
  tags: packages, install

- name: Install non-gui packages
  when: not gui_enabled
  apt: name={{item}} state=installed
  with_items:
    - vim-nox
  tags: packages, install

- name: Set default X session in lightdm
  when: gui_enabled and gui_session
  ini_file:
    dest: /etc/lightdm/lightdm.conf
    section: SeatDefaults
    option: user-session
    value: "{{gui_session}}"
    backup: true

- name: Enable and start lightdm
  when: gui_enabled
  service:
    name: lightdm
    enabled: yes
    state: started
