---

- include: dist-debian.yml
  when: ansible_os_family == 'Debian'

- name: "Sync system ssh_known_hosts"
  copy:
    src:  ssh_known_hosts
    dest: /etc/ssh/ssh_known_hosts
    mode: 0644
  tags: ssh
