---

- name: add python-apt
  apt: name=python-apt state=installed

# Not used here, but nice to have ready
- name: add backports repo
  apt_repository:
    repo: "deb http://http.debian.net/debian {{ansible_distribution_release}}-backports main"
  tags: repos

- name: add pgdg repo
  when: ansible_architecture in ["i386", "x86_64"]
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main"
  tags: repos

- name: apt upgrade
  apt: upgrade=yes update_cache=yes cache_valid_time=3600 
  tags: packages, upgrade

